### ISSUE TITLE
sci-electronics/gazebo-7.1.0 cmake errors

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#18] opened 2017-04-16 00:56 UTC
with ignition-math-3.1.0 and sdformat-5.1.0 configure phase fails with

```
CMake Warning at cmake/SearchForStuff.cmake:536 (find_package):
  Could not find a configuration file for package "SDFormat" that is
  compatible with requested version "4.1.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/sdformat/SDFormatConfig.cmake, version: 5.1.0
    /usr/lib/cmake/sdformat/SDFormatConfig.cmake, version: 5.1.0

Call Stack (most recent call first):
  CMakeLists.txt:128 (include)


-- Looking for SDFormat - not found
--      Missing: SDF version >=4.1.0. Required for reading and writing SDF files.
```

and

```
-- Looking for ignition-math2-config.cmake - not found
--      Missing: Ignition math2 library.
--      Missing: Ignition Transport (libignition-transport0-dev)
```

```
-- BUILD ERRORS: These must be resolved before compiling.
--      Missing: SDF version >=4.1.0. Required for reading and writing SDF files.
--      Missing: Ignition math2 library.
-- END BUILD ERRORS
```

**Comment by Alessandro-Barbieri** [comment] 2017-05-10 21:05
well, downstream version `8.1.0` build, so I don't need this more

**Comment by allenh1** [comment] 2017-05-10 21:08
Version 7 is still needed for support with Kinetic.

**Comment by allenh1** [comment] 2017-05-25 01:17
Update: version 7 is also necessary for use with lunar. But, that said, I think the ebuild is working now if you want to verify.

**Comment by allenh1** [comment] 2017-06-25 00:10
Closing this, since we have a working Gazebo 7.8 build.

**Closed by allenh1** 2017-06-25 00:10 UTC

**Comment by mhallak** [comment] 2017-09-06 11:25
I am trying to run: http://gazebosim.org/tutorials?tut=parallel&cat=physics
I have the following problem:
`-- ----------------------------------------

-- BUILD WARNINGS
-- 	OpenAL not found, audio support will be disabled.
-- 	HDF5 not found
-- 	DART not found, for dart physics engine option, please install libdart-core4-dev.
-- 	libswscale not found. Audio-video capabilities will be disabled.
-- 	libavformat not found. Audio-video capabilities will be disabled.
-- 	libavcodec not found. Audio-video capabilities will be disabled.
-- 	libavutil not found. Audio-video capabilities will be disabled.
-- 	Player not found, gazebo plugin for player will not be built.
-- 	libusb-1.0 not found. USB peripherals support will be disabled.
-- 	Oculus Rift support will be disabled.
-- 	GDAL not found, Digital elevation terrains support will be disabled.
-- 	Graphviz not found, Model editor's schematic view will be disabled.
-- END BUILD WARNINGS

-- BUILD ERRORS: These must be resolved before compiling.
-- 	Missing: SDF version >=4.1.0. Required for reading and writing SDF files.
-- 	Missing: Ignition math2 library.
-- END BUILD ERRORS

CMake Error at CMakeLists.txt:289 (message):
  Errors encountered in build.  Please see the BUILD ERRORS above.


-- Configuring incomplete, errors occurred!
See also "/home/robil/gazebo_parallel/build_isolated/gazebo/devel/CMakeFiles/CMakeOutput.log".
See also "/home/robil/gazebo_parallel/build_isolated/gazebo/devel/CMakeFiles/CMakeError.log".
<== Failed to process package 'gazebo': 
  Command '['/home/robil/gazebo_parallel/devel_isolated/sdformat/env.sh', 'cmake', '/home/robil/gazebo_parallel/src/gazebo', '-DCMAKE_INSTALL_PREFIX=/home/robil/gazebo_parallel/devel_isolated/gazebo', '-DENABLE_DIAGNOSTICS=1', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/robil/gazebo_parallel/build_isolated/gazebo && /home/robil/gazebo_parallel/devel_isolated/sdformat/env.sh cmake /home/robil/gazebo_parallel/src/gazebo -DCMAKE_INSTALL_PREFIX=/home/robil/gazebo_parallel/devel_isolated/gazebo -DENABLE_DIAGNOSTICS=1 -G 'Unix Makefiles'
`
I will be delighted if someone could help me getting a idea about how to solve that...

**Comment by allenh1** [comment] 2017-09-06 13:50
@mhallak If I remember correctly, the issue was simply that the sdformat library was sdf5 instead of sd4.

You might try building [SDF-4.3.2](https://bitbucket.org/osrf/sdformat/get/sdformat4_4.3.2.tar.bz2).

```
-- BUILD ERRORS: These must be resolved before compiling.
-- 	Missing: SDF version >=4.1.0. Required for reading and writing SDF files.
-- 	Missing: Ignition math2 library.
-- END BUILD ERRORS
```

**Comment by mhallak** [comment] 2017-09-12 15:37
@allenh1 Thank you
Should I merge with gazebo 7.8 ? I have gazebo 7.7.0 and it crashes.
[question](http://answers.gazebosim.org/question/17243/parallel-physics-gazebo-770-ros-kinetic-ubuntu-16/)

**Comment by allenh1** [comment] 2017-09-12 16:34
> Should I merge with gazebo 7.8 ? I have gazebo 7.7.0 and it crashes.

That would depend on the ROS distro you're using.

That said, I'm not sure why 7.7.0 crashes, but I would try updating first (unless you're using an older ROS version).
